# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160313_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WechatUesr',
            new_name='WechatUser',
        ),
    ]
