# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160313_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatuser',
            name='msg_state',
            field=models.IntegerField(default=10),
        ),
    ]
